[versions]
# Project
android_gradle_plugin = "7.4.2"
kotlin = "1.8.10"

# Plugins
ksp = "1.7.22-1.0.8"

# AndroidX
corektx = "1.9.0"

# Compose
compose = "2023.01.00"
compose_compiler = "1.4.3"
compose_activity = "1.6.1"


[libraries]
# Project
android_gradle_plugin = { module = "com.android.tools.build:gradle", version.ref = "android_gradle_plugin" }
kotlin_gradle_plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

# AndroidX
androidx_corektx = { module = "androidx.core:core-ktx", version.ref = "corektx" }

# Compose
compose_bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
compose_ui = { module = "androidx.compose.ui:ui" }
compose_ui_tooling = { module = "androidx.compose.ui:ui-tooling" }
compose_toolingpreview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose_activity = { module = "androidx.activity:activity-compose", version.ref = "compose_activity" }
compose_material3 = { module = "androidx.compose.material3:material3" }

[bundles]
compose = ["compose.ui", "compose.toolingpreview", "compose.activity", "compose.material3"]

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
